### ISSUE TITLE
tidak bisa isi KRS prasyarat karena nilai konversi

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#102]
![error prasyarat bhs inggris](https://user-images.githubusercontent.com/7375037/36137220-cae2ff5a-10c6-11e8-9568-ef24493f4300.png)
nilai bahasa inggris 1 sudah ada di transkrip kurikulum tetapi tidak ada di khs karena konversi

**Comment by mrizkir** [comment]
udah diperbaiki ini.
