### ISSUE TITLE
Install Portalekampus erroe

### ISSUE THREAD

**Issue by penya2nk** [mrizkir/portalekampus#107]
Warning: require_once(C:\wamp\www/framework_323/pradolite.php): failed to open stream: No such file or directory in C:\wamp\www\portalekampus\index.php on line 4

**Comment by mrizkir** [comment]
Mmmh. Itu download terpisah. dari website pradoframework.net. Berdasarkan ini, selanjutnya kami akan sertakan framework dan library yang dibutuhkan.

**Comment by penya2nk** [comment]
siap dan makasih mas bos

**Comment by penya2nk** [comment]
Sampai saat ini saya belum berhasil menginstall bosku

**Comment by mrizkir** [comment]
Udah saya push library prado-nya. Dicoba lagi...
