### ISSUE TITLE
Error Saat mengUpgdrade Framework Prado Versi 3.3.3

### ISSUE THREAD

**Issue by penya2nk** [mrizkir/portalekampus#117]
TApplicationException
Description
Component method 'NilaiUjianPMB.registerPostDataLoader' is not defined.

Source File
/home/stikfamikaac/public_html/e/framework/TComponent.php (560)

0549:         }
0550: 
0551:         if(strncasecmp($method,'dy',2)===0||strncasecmp($method,'fx',2)===0)
0552:         {
0553:             if($this instanceof IDynamicMethods)
0554:                 return $this->__dycall($method,$args);
0555:             return isset($args[0])?$args[0]:null;
0556:         }
0557: 
0558:         // don't thrown an exception for __magicMethods() or any other weird methods natively implemented by php
0559:         if (!method_exists($this, $method)) {
0560:             throw new TApplicationException('component_method_undefined',get_class($this),$method);
0561:         }
0562:     }
0563: 
0564: 
0565:     /**
0566:      * Returns a property value or an event handler list by property or event name.
0567:      * Do not call this method. This is a PHP magic method that we override
0568:      * to allow using the following syntax to read a property:
0569:      * <code>
0570:      * $value=$component->PropertyName;
0571:      * $value=$component->jsPropertyName; // return JavaScript literal
0572:      * </code>

Stack Trace
#0 /home/stikfamikaac/public_html/e/protected/lib/CustomControls/TCustomDatePicker.php(413): TComponent->__call('registerPostDat...', Array)
#1 /home/stikfamikaac/public_html/e/protected/lib/CustomControls/TCustomDatePicker.php(413): NilaiUjianPMB->registerPostDataLoader('ctl0$mainconten...')
#2 /home/stikfamikaac/public_html/e/framework/pradolite.php(4484): TCustomDatePicker->onPreRender(NULL)
#3 /home/stikfamikaac/public_html/e/framework/Web/UI/ActiveControls/TActiveControlAdapter.php(85): TControlAdapter->onPreRender(NULL)
#4 /home/stikfamikaac/public_html/e/framework/pradolite.php(5179): TActiveControlAdapter->onPreRender(NULL)
#5 /home/stikfamikaac/public_html/e/framework/pradolite.php(5187): TControl->preRenderRecursive()
#6 /home/stikfamikaac/public_html/e/framework/pradolite.php(5187): TControl->preRenderRecursive()
#7 /home/stikfamikaac/public_html/e/framework/pradolite.php(5187): TControl->preRenderRecursive()
#8 /home/stikfamikaac/public_html/e/framework/pradolite.php(5187): TControl->preRenderRecursive()
#9 /home/stikfamikaac/public_html/e/framework/pradolite.php(5187): TControl->preRenderRecursive()
#10 /home/stikfamikaac/public_html/e/framework/pradolite.php(5187): TControl->preRenderRecursive()
#11 /home/stikfamikaac/public_html/e/framework/pradolite.php(7598): TControl->preRenderRecursive()
#12 /home/stikfamikaac/public_html/e/framework/pradolite.php(7587): TPage->processNormalRequest(Object(THtmlWriter))
#13 /home/stikfamikaac/public_html/e/framework/pradolite.php(9796): TPage->run(Object(THtmlWriter))
#14 /home/stikfamikaac/public_html/e/framework/pradolite.php(9762): TPageService->runPage(Object(NilaiUjianPMB), Array)
#15 /home/stikfamikaac/public_html/e/framework/pradolite.php(10947): TPageService->run()
#16 /home/stikfamikaac/public_html/e/framework/pradolite.php(10478): TApplication->runService()
#17 /home/stikfamikaac/public_html/e/index.php(6): TApplication->run()
#18 {main}

**Comment by mrizkir** [comment]
Saat ini belum bisa diperbaiki, karena rencananya langsung ke prado versi 4.0.1
