### ISSUE TITLE
Error Kuosisoner di variabel Mahasiswa (mh)

### ISSUE THREAD

**Issue by penya2nk** [mrizkir/portalekampus#121]
Mohon di aktifkan pak master kuesioner di variable mh (mahasiswa)
info
 Info! Query Failed = SELECT idpengampu_penyelenggaraan,iddosen,nidn,nama_dosen FROM v_kelas_mhs WHERE idkrsmatkul= [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1]

Mohon Petunjuk Master

**Comment by mrizkir** [comment]
Kira2 ini ada muncul lagi masalahnya gak ?

**Comment by penya2nk** [comment]
Tidak ada pesan errornya hanya saja tidak aktif mungkin karena tidak ada link ke page nya Pak
