### ISSUE TITLE
Formulir Pendaftaran Mabasiswa Baru

### ISSUE THREAD

**Issue by penya2nk** [mrizkir/portalekampus#124]
**Describe the bug**
Gagal Menghapus formulir Pendaftaran Maba di Page Manajemen

**To Reproduce**

**Comment by mrizkir** [comment]
Pesan errornya gimana ?

**Comment by mrizkir** [comment]
ohya itu di non aktifkan sejak kasus hilang data

**Comment by penya2nk** [comment]
OOOKKKK... siap master....

**Comment by mrizkir** [comment]
Hilang data disebabkan oleh versi MySQL yang ada bug di perintah REPLACE INTO.
Solusinya upgrade MySQL ke Maria DB
