### ISSUE TITLE
Apakah sistem ini masih di kembangkan?

### ISSUE THREAD

**Issue by cloner3000** [mrizkir/portalekampus#130]
saya mau donasi . mohon tutorial untuk instalasinya. Terimakasih

**Comment by cloner3000** [comment]
kirim via email mas kontak Wa nya dan tutorialnya cc doe202687@gmail.com . terimakasih

**Comment by mrizkir** [comment]
Kalau tutorialnya secara khusus belum ada. Secara umum langkah instalasi :
1. Clone project ke document root.
2. Edit file protected/application.xml
3. sesuaikan username dan nama database.

**Comment by mrizkir** [comment]
Nomor WA saya sudah kirim
