### ISSUE TITLE
Mohon ijin ikut kembangkan aplikasi ini pak..

### ISSUE THREAD

**Issue by Handi2290** [mrizkir/portalekampus#134]

**Comment by mrizkir** [comment]
Sori baru balas. Siap. Silahkan.

**Comment by mrizkir** [comment]
Portalekampus 3 ini dikembangkan menggunakan Framework Lumen dan Vue + Vuetify.

**Comment by Handi2290** [comment]
mantap Pak Rizkir.. tapi saya tanya-tanya ntar.. boleh ya

**Comment by Handi2290** [comment]
boleh minta nomor kontak atau email pak?

**Comment by mrizkir** [comment]
boleh. tapi tidak bisa saya sampaikan disini. DM saya di twitter https://twitter.com/m_rizki_r

**Comment by Handi2290** [comment]
![image](https://user-images.githubusercontent.com/54350360/87373358-c0a3ce80-c5b3-11ea-8041-27567a5be8ae.png)

Maaf pak tapi ga bisa saya DM akun twitter bapak..

**Comment by mrizkir** [comment]
kok bisa yah. Kalau facebook https://fb.com/mrizkiromdoni
