### ISSUE TITLE
Ubah Keterangan Isi Kuesioner di Login Mahasiswa menu KHS

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#18]
untuk kolom keterangan :
jika nilai blm di input keterangannya "belum ada nilai" tombol aksi disable
jika nilai sudah di input keterangannya "belum isi kuesioner" tombol aksi aktif

![screenshot_2](https://cloud.githubusercontent.com/assets/7375037/18538743/678ed4aa-7b3b-11e6-81ac-108aba6716c9.png)

**Comment by mrizkir** [comment]
fixed and done.
