### ISSUE TITLE
Error Status Akhir

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#23]
perbaiki status akhir mengikuti daftar ulang di TA terkahir, bukan berdasarkan id proses terkahir
![harusnya statusnya aktif](https://cloud.githubusercontent.com/assets/7375037/19226396/df68f6f2-8ed4-11e6-87e4-bfcef7abba97.png)

**Comment by cahayaonline** [comment]
yang IP belum, contoh NIM 11102049 an. SERI HERIANTI, status masih non aktif

**Comment by mrizkir** [comment]
fixed. untuk datanya diperbaiki secara manual di database.
