### ISSUE TITLE
Error Dobel Nama Mahansiswa

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#25]
TA 2016 Ganjil
![error dobel mahasiswa](https://cloud.githubusercontent.com/assets/7375037/19297209/cd90aecc-906c-11e6-9873-4c0b97da8384.png)

**Comment by mrizkir** [comment]
Dimana letak error ini ?

**Comment by mrizkir** [comment]
di KHS

**Comment by mrizkir** [comment]
Ini terinput dua kali. jadi bukan error.
