### ISSUE TITLE
Error Lihat Nilai di Login Manajemen

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#28]
mahasiswa belum isi kuesioner sehingga manajemen tidak bisa lihat nilai, tidak mungkin menunggu mahasiswa isi kuesioner sedangkan nilai dibutuhkan manajemen untuk dikirim dan diprint 
![tidak bisa lihat nilai di manajemen](https://cloud.githubusercontent.com/assets/7375037/19505522/621df7fe-95ed-11e6-97e3-7b476a7d2a47.png)
sebagai laporan.

**Comment by mrizkir** [comment]
fixed.
