### ISSUE TITLE
ERROR, input keuangan setelah cuti

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#33]
mahasiswa yang CUTI di 2015 genap tidak bisa melakukan pembayaran di 2016 ganjil, contoh nim 12101127 dan nim 15101123
![14618723_1412891838725717_754716634_o](https://cloud.githubusercontent.com/assets/7375037/19716967/98621890-9b88-11e6-85f7-0d7a12ca6943.png)

**Comment by mrizkir** [comment]
fixed
