### ISSUE TITLE
Error Set Mahasiswa Lulus Per TA

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#35]
didaftar ulang khusus ![error lulus](https://cloud.githubusercontent.com/assets/7375037/19842542/8fe49aea-9f4c-11e6-8b48-ab34b9d7d4bb.png)

**Comment by mrizkir** [comment]
nanti diperbaiki di yang baru....

**Comment by cahayaonline** [comment]
untuk status keluar seharusnya data KRS dan Nilai tidak boleh dihapus, harus tetap ada. karena status keluar = pindah, nilainya akan di konversi

contoh nim 06102261 mau di set keluar di 2013 ganjil ternyata ada nilai
![error status pindah belum ada](https://cloud.githubusercontent.com/assets/7375037/20586082/4352180c-b233-11e6-961e-ae2c35b1d3c5.png)

**Comment by mrizkir** [comment]
fixed and added.
