### ISSUE TITLE
Tambah Jumlah Laki-laki dan Perempuan

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#36]
tolong tambahkan jumlah laki-laki dan perempuan 
![jumlah gender](https://cloud.githubusercontent.com/assets/7375037/19878538/5e07bb80-a01c-11e6-974f-9301d8ff9c66.png)
di menu page=m.cube.kemahasiswaan.DaftarMahasiswa

**Comment by mrizkir** [comment]
added.
