### ISSUE TITLE
Error jumlah SKS konversi di akui tidak sama dengan jumlah sks di transkrip kurikulum

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#38]
![screenshot_1](https://cloud.githubusercontent.com/assets/7375037/19994382/53628726-a280-11e6-845f-af8e6c42878a.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/7375037/19994381/536231d6-a280-11e6-94c6-603197f575db.png)

**Comment by mrizkir** [comment]
Hal ini disebabkan karena yang bersangkuta belum mendaftar di Konsentrasi Manajemen Publik. Jadi matakuliahnya tidak di load ke dalam transkrip kurikulum.

**Comment by cahayaonline** [comment]
ini contoh mhsswa udah daftar konsentrasi, tetapi mata kuliah yg di ambil pada semester tidak masuk ke transkrip kurikulum
![screenshot_2](https://cloud.githubusercontent.com/assets/7375037/20590841/16a03d50-b258-11e6-9a90-3735919b84b5.png)
