### ISSUE TITLE
Filter Formulir Mahassiwa Baru

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#42]
Filter berdasarkan program studi yg sudah dan belum daftar ulang per program studi
![screenshot_1](https://cloud.githubusercontent.com/assets/7375037/20128779/4b470c14-a67d-11e6-8603-9d8079cd3d38.png)

**Comment by cahayaonline** [comment]
page=m.cube.spmb.PendaftaranViaWeb

**Comment by mrizkir** [comment]
added.
