### ISSUE TITLE
Error pindah kelas dan Pilih Kelas

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#62]
contoh nim 15102107
pasword : 23041997

kasus:
pada tahun 2016-1 berada di kelas reguler dan belum pilih kelas.
melakukan pindah kelas di tahun 2016-2, berhasil dipindah dari reguler ke karyawan
masalagnya, mau pilih kelas di KRS tahun 2016-1 tidak ada kelas reguler, adanya karyawan
![1](https://cloud.githubusercontent.com/assets/7375037/22234081/db7dce72-e227-11e6-8af6-2a5dd66a743f.png)
![2](https://cloud.githubusercontent.com/assets/7375037/22234082/dc2fad04-e227-11e6-97c6-1f48f37db64f.png)

**Comment by mrizkir** [comment]
query kelasnya berdasarkan status kelas terakhir. jadi akan dirubah menjadi status kelas saat daftar ulang

**Comment by mrizkir** [comment]
fixed.
