### ISSUE TITLE
Pisahkan Print Summary KHS extention 

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#66]
Print out Sumary KHS kelas extention masih campur dengan kelas reguler/karyawan di menu NILAI=>KHS Extention

Print out Summary KHS  kelas reguler/karyawan masih campur dengan kelas extention di menu NILAI=>KHS

**Comment by mrizkir** [comment]
Ini tidak bisa dilakukan karena bersifat global methodnya. Solusinya hanya urutan mahasiswa didasarkan pada kelas, sehingga lebih mudah menghapus data yang tidak diperlukan.
