### ISSUE TITLE
Error di login mhsswa, setelah cuti bisa ambil 24 sks

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#68]
contoh nim 15102015, di TA. 2016 Ganjil CUTI, mau isi KRS di 2016 Genap bisa 24 sks

![ayu novi_2](https://cloud.githubusercontent.com/assets/7375037/22579340/fbf52b00-ea01-11e6-88c9-ef921cf1f6db.png)
![ayu novi_3](https://cloud.githubusercontent.com/assets/7375037/22579341/fc125d2e-ea01-11e6-92a7-b36ad47a85e2.png)
![error novi](https://cloud.githubusercontent.com/assets/7375037/22579342/fc26e87a-ea01-11e6-9e23-829a83cd903c.png)

**Comment by mrizkir** [comment]
fixed
