### ISSUE TITLE
Tambahkan Filter Kelas dan Print Exel per kelas di Peserta Mata Kuliah

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#69]
![tambah peserta mata kuliah](https://cloud.githubusercontent.com/assets/7375037/22580260/71a08ad2-ea09-11e6-8d5a-ee24a777c8d5.png)

**Comment by cahayaonline** [comment]
Tambahkan juga kolom Jenis Kelamin disebelah nama mahasiswa.

**Comment by cahayaonline** [comment]
Buatkan print out peserta mata kuliah

**Comment by mrizkir** [comment]
added.

**Comment by cahayaonline** [comment]
Tlong tambahkan kolom NIRM, JK, dan PILIHAN KELAS, di pserta mata kuliah dan print exel nya ...

![screenshot_4](https://cloud.githubusercontent.com/assets/7375037/23639093/0968b462-0318-11e7-8f89-c62af79d142d.png)
