### ISSUE TITLE
Error belum isi KRS tapi udah klik Tambah

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#71]
jika mahssiwa belum isi KRS tapi udah klik tambah, mahasiswa sudah dikatakan mengisi KRS

![juliati_1](https://cloud.githubusercontent.com/assets/7375037/22820786/d65ffbe6-efaa-11e6-81b9-d53cd50122e3.png)
14101110

**Comment by mrizkir** [comment]
Iya memang seperti itu. karena setelah klik tambah maka dianggap telah mengisi KRS. Untuk saat ini akan dibiarkan keadaanya seperti ini.
