### ISSUE TITLE
Error IPK sem. 1 tidak sama dengan IPS

### ISSUE THREAD

**Issue by cahayaonline** [mrizkir/portalekampus#72]
![error ipk sem 1](https://cloud.githubusercontent.com/assets/7375037/22871749/6a08d1b4-f1e6-11e6-91fb-1cdbe9761df8.png)

**Comment by mrizkir** [comment]
ini disebabkan oleh mahasiswanya belum isi kuesioner. nanti kalau isi kuesioner semuanya nilai IPS dan IPK akan sama.
