### ISSUE TITLE
Mahasiswa baru data kelas tidak sinkron

### ISSUE THREAD

**Issue by mrizkir** [mrizkir/portalekampus#99]
Kadang - kadang terjadi mahasiswa dengan nomor formulir dari kelas tertentu terdaftar di kelas lain. Oleh karena itu solusinya mencegah mahasiswa baru untuk memilih kelas, dan pilihan kelas mengikat ke pin.

**Comment by cahayaonline** [comment]
berarti pilihan kelas di formulir harus mati, karena milih kelasnya di pin ...
